version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000 # use internal IP if you are running frontend on different machine
    depends_on:
      - backend
    networks:
      - app-net
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/activityTracker
    depends_on:
      - mongo
    networks:
      - app-net
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
